# Generated by Django 2.2 on 2020-01-27 18:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0003_auto_20200127_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='date',
        ),
        migrations.AddField(
            model_name='test',
            name='in_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 27, 23, 37, 18, 128796)),
        ),
    ]
