# Generated by Django 2.2 on 2020-01-27 18:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0004_auto_20200127_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='out_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='in_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 27, 23, 38, 31, 346933)),
        ),
    ]
