# Generated by Django 2.2 on 2020-01-27 18:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0006_auto_20200127_2359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idNumber', models.CharField(max_length=15)),
                ('in_time', models.DateTimeField(default=datetime.datetime(2020, 1, 28, 0, 4, 34, 338019))),
                ('out_time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='test',
        ),
    ]
