# Generated by Django 2.2 on 2020-01-27 18:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0007_auto_20200128_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='in_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 28, 0, 13, 32, 765648)),
        ),
    ]
