# Generated by Django 2.2 on 2020-01-27 19:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0008_auto_20200128_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='in_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 28, 0, 57, 5, 256563)),
        ),
    ]
