# Generated by Django 2.2 on 2020-01-27 19:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0010_auto_20200128_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='in_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 28, 1, 21, 41, 794586)),
        ),
    ]
